import React from "react"
import ReactMde from "react-mde"
import Showdown from "showdown"

export default function Editor({ currentNote, updateNote }) {
    const [selectedTab, setSelectedTab] = React.useState("write")
    // Showdown is a JavaScript Markdown to HTML converter
    // For more info visit : https://github.com/showdownjs/showdown
    const converter = new Showdown.Converter({
        tables: true,
        simplifiedAutoLink: true,
        strikethrough: true,
        tasklists: true,
    })  

    return (
        <section className="pane editor shadow">
            <ReactMde
                value={currentNote.body}
                onChange={updateNote}
                selectedTab={selectedTab}
                onTabChange={setSelectedTab}
                generateMarkdownPreview={(markdown) =>
                    Promise.resolve(converter.makeHtml(markdown))
                }//this callback coverts the markdown generated by the notes app into HTML, it returns a resolved promise
                editorHeight={90}
                heightUnits="vh"
            />
        </section>
    )
}
